name: blue-sushi
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-nvidia
image-version: latest

########################################################
# Module configuration, executed in order.
########################################################
modules:
  - from-file: gnome/extensions.yml
  - from-file: gnome/themes-deps.yml
  - from-file: gnome/install-theme.yml
  - from-file: shell/install.yml
  - from-file: apps/1password.yml
  - from-file: apps/install.yml

  # This sets up the proper policy & signing files for signed images to work fully.
  - type: signing
